### ISSUE TITLE
Assertion failure in activation_free

### ISSUE THREAD

**Issue by Keruspe** [bus1/dbus-broker#13]
```
#0  0x00007fc6f8fa7620 in raise () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6                            
No symbol table info available.                                                                           
#1  0x00007fc6f8fa8ca0 in abort () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6                            
No symbol table info available.                                                                           
#2  0x00007fc6f8fa045a in __assert_fail_base () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6               
No symbol table info available.                                                                           
#3  0x00007fc6f8fa04d2 in __assert_fail () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6                    
No symbol table info available.                                                                           
#4  0x000000000040bc09 in activation_free (activation=0xc60a20) at ../dbus-broker-scm/src/activation.c:71 
        __PRETTY_FUNCTION__ = "activation_free"                                                           
#5  0x000000000040bf28 in activation_registry_flush (registry=0xc5f058) at ../dbus-broker-scm/src/activation.c:141                                                                                                   
        activation = 0xc60a20                                                                             
        safe = 0x0                                                                                        
#6  0x0000000000404cc8 in manager_run (manager=0xc5f010) at ../dbus-broker-scm/src/broker/manager.c:218   
        signew = {__val = {16386, 0 <repeats 15 times>}}                                                  
        sigold = {__val = {81922, 12972376, 0, 0, 4307939624, 140725417619688, 140725417619744, 4213473, 30064771072, 140725417619760, 16386, 0, 0, 0, 0, 0}}                                                        
        listener = 0x0                                                                                    
        safe = 0x7ffd30873268                                                                             
        r = -131                                                                                          
        __func__ = "manager_run"                                                                          
#7  0x0000000000403e1f in run () at ../dbus-broker-scm/src/broker/main.c:121                              
        manager = 0xc5f010                                                                                
        r = 0                                                                                             
        __func__ = "run"                                                                                  
#8  0x0000000000403e9b in main (argc=4, argv=0x7ffd30873268) at ../dbus-broker-scm/src/broker/main.c:133  
        r = 0                                                                                             
        __func__ = "main"                                         
```

**Comment by dvdhrm** [comment]
Just out of curiosity: How did you trigger this? I think this can only be triggered on deamon shutdown, right?

**Comment by Keruspe** [comment]
I hit it on every bootup, when gdm appears
