### ISSUE TITLE
Build depends on git?

### ISSUE THREAD

**Issue by jengelh** [bus1/dbus-broker#61]
```
[   20s] + /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/lib --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload . build
[   20s] Traceback (most recent call last):
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 338, in run
[   20s]     app.generate()
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 181, in generate
[   20s]     intr.run()
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 2728, in run
[   20s]     super().run()
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 148, in run
[   20s]     self.evaluate_codeblock(self.ast, start=1)
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 170, in evaluate_codeblock
[   20s]     raise e
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 164, in evaluate_codeblock
[   20s]     self.evaluate_statement(cur)
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 177, in evaluate_statement
[   20s]     return self.assignment(cur)
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 572, in assignment
[   20s]     value = self.evaluate_statement(node.value)
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 175, in evaluate_statement
[   20s]     return self.function_call(cur)
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 385, in function_call
[   20s]     return self.funcs[func_name](node, self.flatten(posargs), kwargs)
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 77, in wrapped
[   20s]     return f(s, node_or_state, args, kwargs)
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreterbase.py", line 55, in wrapped
[   20s]     return f(self, node, args, kwargs)
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1625, in func_subproject
[   20s]     return self.do_subproject(dirname, kwargs)
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/interpreter.py", line 1637, in do_subproject
[   20s]     resolved = r.resolve(dirname)
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 123, in resolve
[   20s]     if self.resolve_git_submodule(dirname):
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 154, in resolve_git_submodule
[   20s]     ret, out = quiet_git(['rev-parse'], self.subdir_root)
[   20s]   File "/usr/lib/python3.6/site-packages/mesonbuild/wrap/wrap.py", line 43, in quiet_git
[   20s]     stdout=subprocess.PIPE, stderr=subprocess.PIPE)
[   20s]   File "/usr/lib64/python3.6/subprocess.py", line 707, in __init__
[   20s]     restore_signals, start_new_session)
[   20s]   File "/usr/lib64/python3.6/subprocess.py", line 1333, in _execute_child
[   20s]     raise child_exception_type(errno_num, err_msg)
[   20s] FileNotFoundError: [Errno 2] No such file or directory: 'git'
[   20s] The Meson build system
[   20s] Version: 0.42.0
[   20s] Source dir: /home/abuild/rpmbuild/BUILD/dbus-broker-4
[   20s] Build dir: /home/abuild/rpmbuild/BUILD/dbus-broker-4/build
[   20s] Build type: native build
[   20s] Project name: dbus-broker
[   20s] Native C compiler: cc (gcc 7.2.1)
[   20s] Appending CFLAGS from environment: '-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g'
[   20s] Build machine cpu family: x86_64
[   20s] Build machine cpu: x86_64
[   20s] error: Bad exit status from /var/tmp/rpm-tmp.5TOu6B (%build)
```

**Comment by dvdhrm** [comment]
Can you explain how you triggered this? Is this a git-checkout? Or did you use an archive?

So meson has this feature where it can fetch/update submodules automatically. It does it if it sees a `.git` context in the project root. I would guess this can be disabled somehow via `--wrap-mode`, but I am not entirely sure.

You should be able to build `dbus-broker` using archives rather than git-checkouts. If not, either report it to `meson` or add `git` to your build-dependencies.

**Comment by jengelh** [comment]
Just took the v4 .tar.gz link on https://github.com/bus1/dbus-broker/releases

**Comment by dvdhrm** [comment]
This issue is not related to how dbus-broker employs meson. If the `--wrap-mode` cannot be used to circumvent meson from using git, I recommend making git a dependency of `meson` in your package manager. Alternatively, file a bug upstream.

If there is something we as downstream user of meson can do to avoid this, please let us know by reopening this bug. I will close the bug now, as I don't see how this is under our control. Sorry!

**Comment by jengelh** [comment]
[use-system-deps.diff.txt](https://github.com/bus1/dbus-broker/files/1356163/use-system-deps.diff.txt)
Is the workaround that put meson back into sane behavior for me.

**Comment by dvdhrm** [comment]
I cannot reproduce your issue with archives. I can only reproduce it in git-checkouts. If I run `meson` in a v4 tarball, I simply get:

```
Meson encountered an error in file meson.build, line 19, column 0:
Subproject directory 'subprojects/c-dvar' does not exist and cannot be downloaded:
No c-dvar.wrap found for 'subprojects/c-dvar'
```

If I then download a c-dvar (or other subproject) tarball into `src/subprojects/`, the build works without calling into git. Maybe you cloned the subprojects via git? Even looking through meson-code, I don't see that this behavior changed in its history. Only if `git rev-parse` succeeds, it calls into git. Are you sure there is no `.git` directory anywhere?

Regardless, I filed a bug-report upstream, since this is not acceptable behavior, imho. https://github.com/mesonbuild/meson/issues/2425

**Comment by jengelh** [comment]
What I think happens:
meson is being told by
```
sub_cdvar = subproject('c-dvar', version: '>=1')
```
that the `subprojects/c-dvar/` subdirectory needs to have a `.git` directory. Because the github-generated archive does not contain any files in `subprojects/c-dvar/`, but _does_ include the `.gitmodules` file, meson tries to run `git submodule` to download them — which is never going to work in a network-isolated build host (island test).

So I removed the `subproject(...)` line as per the posted patch. The package then compiles fine, because c-dvar is already available (in the right version, too) through the standard paths in `/usr`.
